# 1. URL kết nối: Bắt buộc phải có tham số ssl và sslmode
spring.datasource.url=jdbc:postgresql://dpg-d7a1o26dqaus73aom1bg-a.singapore-postgres.render.com/nhom1db_vf0v?ssl=true&sslmode=require

# 2. Thông tin đăng nhập
spring.datasource.username=nhom1db_user
spring.datasource.password=sinHy4Mzsin1AdS231c3TZpKEoPHcMAV
spring.datasource.driver-class-name=org.postgresql.Driver

# 3. Ép Hibernate dùng Dialect (để bỏ qua bước tự dò metadata - bước đang gây lỗi)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

# 4. Cấu hình HikariCP "kiên nhẫn" hơn
# Tăng thời gian chờ lên 60 giây vì kết nối đi Singapore (Render) có thể bị chậm
spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.leak-detection-threshold=2000

# 5. Bug
server.error.include-message=always
server.error.include-binding-errors=always