spring.datasource.url=jdbc:postgresql://localhost:5432/nhasach_db
spring.datasource.username=nhasach_db_user
spring.datasource.password=o3WWDULwYH79xdqMrppq2hjBlIgQ0MYk
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.create=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
