# 1. URL PHẢI SẠCH (Không chứa username/password)
# Lưu ý: Thêm .singapore-postgres.render.com hoặc .oregon-postgres.render.com tùy vào database của bạn
spring.datasource.url=jdbc:postgresql://dpg-d78ef78ule4c73a1g4o0-a.singapore-postgres.render.com:5432/nhasach_db?sslmode=require
# 2. Khai báo username và password riêng biệt ở đây
spring.datasource.username=nhasach_db_user
spring.datasource.password=o3WWDULwYH79xdqMrppq2hjBlIgQ0MYk

# 3. Các cấu hình bổ trợ
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true